#!/usr/bin/env bash
# script to install nginx
sudo apt update
sudo apt install nginx -y
sudo ufw allow 22
sudo ufw allow 80
sudo ufw --force enable
sudo ufw status
systemctl status nginx
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
