#!/usr/bin/env bash
# Install nginx web server
sudo apt update
sudo apt install -y nginx

# index.html
echo "Hello World!" | sudo tee -a /var/www/html/index.html

# redirect 301
sudo sed -i '36a rewrite ^/redirect_me https://youtu.be/MzlSVFtxb4c permanent;' /etc/nginx/sites-available/default

echo -e "Ceci n'est pas une page\n" | sudo tee /usr/share/nginx/html/404.html
sudo sed -i 's|#error_page 404 \/404.html|error_page 404 \/404.html|' /etc/nginx/sites-available/default
sudo service nginx start 
