#!/usr/bin/env bash
# script to display "Best School" 9 times and after 9th iteration display "Hi"
i=0
while ((i<10)); do 
	if [ "$i" == 9 ]; then
	   	echo Hi 
	fi 
	echo Best School 
	i=$((i+1))
done
